### ISSUE TITLE
Rebuilding a fresh CLI does not find commands on windows

### ISSUE THREAD

**Issue by NirajOzaTech** [dht/gdi#247]
gdi rebuild 
How to rebuild project
After running **“gdi rebuild”** it shows 0 commands found in path.

![Screenshot (263)](https://user-images.githubusercontent.com/122431825/211740638-8b0282f8-5548-4a75-8659-7955c69d00ec.png)

**Comment by dht** [comment]
Hey @NirajOzaTech, nice to meet you, 
I am moving this issue to [this repo](https://github.com/dht/gdi-cli/issues/5)
